# Create mysql database
services:
  mysql:
    image: mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=bus_booking_users_db
      - MYSQL_USER=users
      - MYSQL_PASSWORD=users
